export const hazards: {[key: string]: string} = {
  avln: "avalanche",
  cfld: "coastal_flooding",
  cwav: "cold_wave",
  drgt: "drought",
  erqk: "earthquake",
  hail: "hail",
  hwav: "heat_wave",
  hrcn: "hurricane",
  istm: "ice_storm",
  lnds: "landslide",
  ltng: "lightning",
  rfld: "riverine_flooding",
  swnd: "strong_wind",
  trnd: "tornado",
  tsun: "tsunami",
  vlcn: "volcanic_activity",
  wfir: "wildfire",
  wntw: "winter_weather"
}